/**
 * @file ssi.c
 * @brief A simple shell interpreter
 *
 * 
 * @author lexph
 * @date June 15, 2025
 * 
 * @section Acknowledgment
 * All function-level comments in this file were generated by Microsoft Copilot.
*/

#include "ssi.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <readline/readline.h>

int main() {
    signal(SIGINT, SIG_IGN);
    while (1) {
        reap_bg_processes();

        char *prompt = generate_prompt();
        if (!prompt) return EXIT_FAILURE;

        char *input = readline(prompt);
        safe_free((void **) &prompt);
        if (!input) {
            printf("\n");
            return EXIT_SUCCESS;
        }

        shell_status status = STATUS_CONTINUE;
        char **argv = tokenize(input);
        if (argv && argv[0]) {
            builtin_func func = get_builtin(argv[0]);
            if (func) {
                status = func(argv);
            } else {
                status = run_command(argv[0], argv, 0);
            }
        }

        free(argv);
        free(input);

        if (status == STATUS_EXIT_SUCCESS) {
            cleanup();
            return EXIT_SUCCESS;
        } else if (status == STATUS_EXIT_FAILURE) {
            cleanup();
            return EXIT_FAILURE;
        }
    }
}
